{"project-id": 1234, "headers": {"Host": "localhost:5000", "Accept-Encoding": "identity", "Sentry-Trace": "78e33b67bb1d4771916b2bf53dba47ad-94b6087babc642b7-", "Content-Length": "1017", "Content-Type": "application/json", "Content-Encoding": "gzip", "User-Agent": "sentry.python/1.1.0", "X-Sentry-Auth": "Sentry sentry_key=examplePublicKey, sentry_version=7, sentry_client=sentry.python/1.1.0"}, "data": {"level": "error", "exception": {"values": [{"module": null, "type": "ZeroDivisionError", "value": "division by zero", "mechanism": {"type": "excepthook", "handled": false}, "stacktrace": {"frames": [{"filename": "capture_exception_on_error.py", "abs_path": "/home/panagiotis/development/projects/exercises/sentry_server/capture_exception_on_error.py", "function": "<module>", "module": "__main__", "lineno": 13, "pre_context": ["    # of transactions for performance monitoring.", "    # We recommend adjusting this value in production.", "    traces_sample_rate=1.0,", ")", ""], "context_line": "division_by_zero = 1 / 0", "post_context": [], "vars": {"__name__": "'__main__'", "__doc__": "None", "__package__": "None", "__loader__": "<_frozen_importlib_external.SourceFileLoader object at 0x7f19d67f2df0>", "__spec__": "None", "__annotations__": {}, "__builtins__": "<module 'builtins' (built-in)>", "__file__": "'capture_exception_on_error.py'", "__cached__": "None", "sentry_sdk": "<module 'sentry_sdk' from '/home/panagiotis/development/projects/exercises/sentry_server/virtualenv/lib/python3.8/site-packages/sentry_sdk/__init__.py'>"}, "in_app": true}]}}]}, "event_id": "1040eaf42aa547cfa2d65b3badc17ecb", "timestamp": "2021-08-22T17:53:38.207486Z", "breadcrumbs": {"values": []}, "contexts": {"runtime": {"name": "CPython", "version": "3.8.6", "build": "3.8.6 (default, Sep 25 2020, 00:00:00) \n[GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]"}}, "modules": {"wheel": "0.36.2", "werkzeug": "2.0.1", "urllib3": "1.26.5", "setuptools": "57.0.0", "sentry-sdk": "1.1.0", "pip": "21.1.2", "markupsafe": "2.0.1", "jinja2": "3.0.1", "itsdangerous": "2.0.1", "flask": "2.0.1", "click": "8.0.1", "certifi": "2021.5.30"}, "extra": {"sys.argv": ["capture_exception_on_error.py"]}, "environment": "production", "server_name": "dhcppc5", "sdk": {"name": "sentry.python", "version": "1.1.0", "packages": [{"name": "pypi:sentry-sdk", "version": "1.1.0"}], "integrations": ["argv", "atexit", "dedupe", "excepthook", "logging", "modules", "stdlib", "threading"]}, "platform": "python"}}
