{"project-id": 1234, "headers": {"Host": "localhost:5000", "Accept-Encoding": "identity", "Sentry-Trace": "c23a408eb7be4b839afffd3a4f6d5708-8ff5f65dbdea75d0-", "Content-Length": "537", "Content-Type": "application/json", "Content-Encoding": "gzip", "User-Agent": "sentry.python/1.1.0", "X-Sentry-Auth": "Sentry sentry_key=examplePublicKey, sentry_version=7, sentry_client=sentry.python/1.1.0"}, "data": {"message": "Something went wrong", "level": "info", "event_id": "ce3c039862894e159e7ba39046dc2169", "timestamp": "2021-08-22T18:14:39.662177Z", "breadcrumbs": {"values": []}, "contexts": {"runtime": {"name": "CPython", "version": "3.8.6", "build": "3.8.6 (default, Sep 25 2020, 00:00:00) \n[GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]"}}, "modules": {"wheel": "0.36.2", "werkzeug": "2.0.1", "urllib3": "1.26.5", "setuptools": "57.0.0", "sentry-sdk": "1.1.0", "pip": "21.1.2", "markupsafe": "2.0.1", "jinja2": "3.0.1", "itsdangerous": "2.0.1", "flask": "2.0.1", "click": "8.0.1", "certifi": "2021.5.30"}, "extra": {"sys.argv": ["capture_message.py"]}, "environment": "production", "server_name": "dhcppc5", "sdk": {"name": "sentry.python", "version": "1.1.0", "packages": [{"name": "pypi:sentry-sdk", "version": "1.1.0"}], "integrations": ["argv", "atexit", "dedupe", "excepthook", "logging", "modules", "stdlib", "threading"]}, "platform": "python"}}
